module.exports = {
  parent_name: "Mr. Sharma",
  child_name: "Aarav",
  grade: "Class 11",
  board: "CBSE",
  demo_subject: "Physics",
  demo_teacher: "Ms. Kapoor",
  weak_topic: "Rotational Motion",
  exam_target: "JEE",
  exam_date: "2027",
  preferred_language: "hi-IN",
  fee_amount: "forty-two thousand rupees",
  batch_options: "weekday evening, weekend morning",
  enrolment_link: "(mock — speak it, don't send)",
  payment_plan_available: true,
  scholarship_available: false,
  second_session_available: true,
  senior_callback_available: true,
};
